import { createHash } from "node:crypto";
import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import Ajv2020 from "ajv/dist/2020.js";

const MODULE_PATH = import.meta.url.startsWith("file:") ? fileURLToPath(import.meta.url) : "";
const DEFAULT_ROOT = MODULE_PATH ? path.resolve(path.dirname(MODULE_PATH), "..") : path.resolve(process.cwd());
const EXPECTED_PRODUCTS = ["home", "tech", "travel", "life"];
const TEXT_EXTENSIONS = new Set([".css", ".html", ".js", ".json", ".mjs", ".svg"]);

function stable(value) {
  if (Array.isArray(value)) return value.map(stable);
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.keys(value).sort().map((key) => [key, stable(value[key])]));
  }
  return value;
}

function json(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function normalizedBytes(file, bytes) {
  if (!TEXT_EXTENSIONS.has(path.extname(file))) return bytes;
  return Buffer.from(bytes.toString("utf8").replace(/^\uFEFF/, "").replace(/\r\n?/g, "\n"));
}

function moduleSource(name, value) {
  return `// Generated by scripts/generate-site.mjs. Do not edit.\nexport const ${name} = ${JSON.stringify(value, null, 2)};\n`;
}

function assertUnique(items, field, label) {
  const values = items.map((item) => item[field]);
  if (new Set(values).size !== values.length) throw new Error(`${label} contain duplicate ${field} values`);
}

function validateCompleteness(manifest) {
  const ordered = [...manifest.pages].sort((a, b) => a.order - b.order);
  if (ordered.map(({ id }) => id).join(",") !== EXPECTED_PRODUCTS.join(",")) {
    throw new Error(`product pages must be exactly ${EXPECTED_PRODUCTS.join(", ")} in order`);
  }
  assertUnique(manifest.pages, "id", "product pages");
  assertUnique(manifest.pages, "route", "product pages");
  assertUnique(manifest.pages, "document", "product pages");
  assertUnique(manifest.pages, "order", "product pages");
  assertUnique(manifest.utilities, "id", "utilities");
  assertUnique(manifest.utilities, "route", "utilities");
  assertUnique(manifest.utilities, "document", "utilities");
  const allRoutes = [...manifest.pages, ...manifest.utilities];
  assertUnique(allRoutes, "route", "all routes");
  assertUnique(allRoutes, "document", "all routes");
  if (manifest.pages.some(({ tier }) => tier !== "primary")) {
    throw new Error("navigation must contain only primary products");
  }
  const utilities = new Map(manifest.utilities.map((item) => [item.id, item]));
  if (!utilities.has("not-found") || !utilities.has("offline")) throw new Error("not-found and offline utilities are mandatory");
  assertUnique(manifest.assets, "path", "assets");
}
function dependencySpecifiers(file, source) {
  if (path.extname(file) === ".css") {
    return [...source.matchAll(/@import\s+(?:url\(\s*)?["']([^"']+)["']\s*\)?/g)].map((match) => match[1]);
  }
  if (![".js", ".mjs"].includes(path.extname(file))) return [];
  const specs = [];
  const staticPattern = /(?:import|export)\s+(?:[^;"']*?\s+from\s*)?["']([^"']+)["']/g;
  const dynamicPattern = /import\(\s*["']([^"']+)["']\s*\)/g;
  for (const match of source.matchAll(staticPattern)) specs.push(match[1]);
  for (const match of source.matchAll(dynamicPattern)) specs.push(match[1]);
  return specs;
}

function resolveDependency(importer, specifier) {
  if (/^(?:[a-z]+:)?\/\//i.test(specifier) || specifier.startsWith("data:")) {
    throw new Error(`external import is not allowed: ${specifier} from ${importer}`);
  }
  const isBare = !specifier.startsWith(".") && !specifier.startsWith("/");
  if (isBare && path.extname(importer) !== ".css") {
    throw new Error(`unresolved bare import: ${specifier} from ${importer}`);
  }
  const clean = specifier.split(/[?#]/, 1)[0];
  const resolved = path.posix.normalize(clean.startsWith("/") ? clean.slice(1) : path.posix.join(path.posix.dirname(importer), clean));
  if (resolved === ".." || resolved.startsWith("../") || path.posix.isAbsolute(resolved)) {
    throw new Error(`import escapes site root: ${specifier} from ${importer}`);
  }
  return resolved;
}

async function exists(file) {
  try { await access(file); return true; } catch { return false; }
}

async function walkAssets(rootDir, roots, virtualFiles) {
  const states = new Map();
  const discovered = new Map();
  const stack = [];

  async function read(relative) {
    if (virtualFiles.has(relative)) return Buffer.from(virtualFiles.get(relative));
    return readFile(path.join(rootDir, ...relative.split("/")));
  }

  async function visit(relative, classification) {
    const previous = discovered.get(relative);
    discovered.set(relative, {
      availability: previous?.availability === "required" || classification.availability === "required" ? "required" : "optional",
      mutability: previous?.mutability ?? classification.mutability,
      cacheRole: previous?.cacheRole === "shell" || classification.cacheRole === "shell" ? "shell" : classification.cacheRole,
    });
    if (states.get(relative) === "visiting") {
      const start = stack.indexOf(relative);
      throw new Error(`cyclic import: ${[...stack.slice(start), relative].join(" -> ")}`);
    }
    if (states.get(relative) === "done") return;
    if (!virtualFiles.has(relative) && !(await exists(path.join(rootDir, ...relative.split("/"))))) {
      throw new Error(`unresolved import or missing mandatory asset: ${relative}`);
    }
    states.set(relative, "visiting");
    stack.push(relative);
    const bytes = await read(relative);
    for (const specifier of dependencySpecifiers(relative, bytes.toString("utf8"))) {
      await visit(resolveDependency(relative, specifier), classification);
    }
    stack.pop();
    states.set(relative, "done");
  }

  for (const root of roots) {
    const present = virtualFiles.has(root.path) || await exists(path.join(rootDir, ...root.path.split("/")));
    if (!present && root.availability === "optional") continue;
    await visit(root.path, root);
  }
  return { discovered, read };
}
function pagesArtifact(manifest) {
  const pages = [...manifest.pages].sort((a, b) => a.order - b.order).map(({ id, label, route, tier }) => ({ id, label, href: route, tier }));
  return moduleSource("PAGES", pages);
}

function routesArtifact(manifest) {
  const products = [...manifest.pages].sort((a, b) => a.order - b.order).map(({ id, route, document }) => ({ id, route, alias: `/${document}` }));
  const utilities = manifest.utilities.map(({ id, route, document, cacheRole }) => ({ id, route, alias: `/${document}`, cacheRole }));
  const aliases = Object.fromEntries([...products, ...utilities].map(({ alias, route }) => [alias, route]));
  return `// Generated by scripts/generate-site.mjs. Do not edit.\nexport const PRODUCT_ROUTE_LIST = ${JSON.stringify(products, null, 2)};\nexport const UTILITY_ROUTE_LIST = ${JSON.stringify(utilities, null, 2)};\nexport const ROUTE_ALIASES = ${JSON.stringify(aliases, null, 2)};\n`;
}

function contentType(file) {
  return ({ ".png": "image/png", ".svg": "image/svg+xml", ".jpg": "image/jpeg", ".JPG": "image/jpeg" })[path.extname(file)] ?? "application/octet-stream";
}

async function routeFixture(manifest, rootDir) {
  const probeAssets = [];
  for (const asset of manifest.assets.filter(({ routeProbe }) => routeProbe)) {
    const bytes = await readFile(path.join(rootDir, ...asset.path.split("/")));
    probeAssets.push({
      path: `/${asset.path}`, contentType: contentType(asset.path), bytes: bytes.byteLength,
      sha256: createHash("sha256").update(bytes).digest("hex"),
    });
  }
  return json({
    version: manifest.schemaVersion, maxRedirects: 2,
    products: [...manifest.pages].sort((a, b) => a.order - b.order).map(({ route, document, h1 }) => ({ path: route, alias: `/${document}`, h1 })),
    utilities: manifest.utilities.map(({ id, route, document, h1 }) => ({ id, path: route, alias: `/${document}`, h1 })),
    assets: probeAssets,
    unknown: { path: "/definitely-missing", h1: manifest.utilities.find(({ id }) => id === "not-found").h1 },
  });
}

function vercelArtifact(manifest) {
  const redirects = manifest.pages.map(({ route, document }) => ({ source: `/${document}`, destination: route, permanent: true }));
  return json({
    "$schema": "https://openapi.vercel.sh/vercel.json",
    buildCommand: manifest.hosting.buildCommand,
    cleanUrls: manifest.hosting.cleanUrls,
    framework: manifest.hosting.framework,
    outputDirectory: manifest.hosting.outputDirectory,
    trailingSlash: manifest.hosting.trailingSlash,
    redirects,
    rewrites: manifest.hosting.rewrites,
    headers: manifest.hosting.headers,
  });
}

function cacheArtifact(manifest, identity, discovered) {
  const required = new Set(manifest.pages.map(({ route }) => route));
  const optional = new Set();
  for (const utility of manifest.utilities.filter(({ cacheRole }) => cacheRole === "shell")) required.add(`/${utility.document}`);
  const metadata = [];
  for (const [file, classification] of [...discovered].sort(([a], [b]) => a.localeCompare(b))) {
    metadata.push({ path: `/${file}`, ...classification });
    if (classification.cacheRole !== "shell") continue;
    (classification.availability === "required" ? required : optional).add(`/${file}`);
  }
  const requiredList = [...required].sort();
  const optionalList = [...optional].filter((item) => !required.has(item)).sort();
  return `// Generated by scripts/generate-site.mjs. Do not edit.\nexport const CACHE_MANIFEST_VERSION = ${manifest.schemaVersion};\nexport const CACHE_NAMESPACE = ${JSON.stringify(manifest.cache.namespace)};\nexport const CACHE_IDENTITY = ${JSON.stringify(identity)};\nexport const REQUIRED_SHELL = ${JSON.stringify(requiredList, null, 2)};\nexport const OPTIONAL_SHELL = ${JSON.stringify(optionalList, null, 2)};\nexport const CACHE_ASSETS = ${JSON.stringify(metadata, null, 2)};\n`;
}
export async function buildSiteArtifacts({ rootDir = DEFAULT_ROOT, manifestPath = path.join(rootDir, "config/site-manifest.json") } = {}) {
  const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
  const schemaPath = path.resolve(path.dirname(manifestPath), manifest.$schema);
  const schema = JSON.parse(await readFile(schemaPath, "utf8"));
  const validate = new Ajv2020({ allErrors: true, strict: true }).compile(schema);
  if (!validate(manifest)) {
    const details = validate.errors.map(({ instancePath, message }) => `${instancePath || "/"} ${message}`).join("; ");
    throw new Error(`site manifest schema validation failed: ${details}`);
  }
  validateCompleteness(manifest);

  const virtualFiles = new Map([
    ["js/generated/pages.js", pagesArtifact(manifest)],
    ["js/generated/routes.js", routesArtifact(manifest)],
  ]);
  const { discovered, read } = await walkAssets(rootDir, manifest.assets, virtualFiles);
  for (const document of [...manifest.pages, ...manifest.utilities].map(({ document }) => document)) {
    if (!(await exists(path.join(rootDir, document)))) throw new Error(`missing mandatory document: ${document}`);
  }

  const identityHash = createHash("sha256");
  const identityManifest = stable({ schemaVersion: manifest.schemaVersion, cache: manifest.cache, pages: manifest.pages, utilities: manifest.utilities, assets: manifest.assets });
  identityHash.update(`manifest\0${JSON.stringify(identityManifest)}\0`);
  const identityFiles = new Set([...discovered.keys(), ...manifest.pages.map(({ document }) => document), ...manifest.utilities.map(({ document }) => document)]);
  for (const file of [...identityFiles].sort()) {
    const bytes = discovered.has(file) ? await read(file) : await readFile(path.join(rootDir, file));
    identityHash.update(file).update("\0").update(normalizedBytes(file, bytes)).update("\0");
  }
  const identity = identityHash.digest("hex").slice(0, 20);
  const artifacts = new Map(virtualFiles);
  artifacts.set("js/generated/cache-manifest.js", cacheArtifact(manifest, identity, discovered));
  artifacts.set("tests/fixtures/route-contract.json", await routeFixture(manifest, rootDir));
  artifacts.set("vercel.json", vercelArtifact(manifest));
  return { artifacts, identity, manifest, discovered };
}

export async function generateSite(options = {}) {
  const { rootDir = DEFAULT_ROOT, check = false } = options;
  const result = await buildSiteArtifacts({ ...options, rootDir });
  const stale = [];
  for (const [relative, content] of result.artifacts) {
    const target = path.join(rootDir, ...relative.split("/"));
    let current = null;
    try { current = await readFile(target, "utf8"); } catch {}
    if (current === content) continue;
    stale.push(relative);
    if (!check) {
      await mkdir(path.dirname(target), { recursive: true });
      await writeFile(target, content, "utf8");
    }
  }
  if (check && stale.length) throw new Error(`generated artifacts are stale: ${stale.join(", ")}`);
  return { ...result, stale };
}

const isCli = MODULE_PATH && process.argv[1] && path.resolve(process.argv[1]) === MODULE_PATH;
if (isCli) {
  const check = process.argv.includes("--check");
  try {
    const result = await generateSite({ check });
    console.log(`${check ? "checked" : "generated"} ${result.artifacts.size} artifacts; cache identity ${result.identity}`);
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
